version: "3"
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: webstat
    ports:
      - 27017:27017
    volumes:
      - ./production/data/db:/data/db
  mongo-dev:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: webstat
    ports:
      - 27018:27017
    volumes:
      - ./development/data/db:/data/db
